services:
  file-server:
    container_name: file-server  
    ports:
      - 11127:5000
    volumes:
      - /DATA/AppData/file-server/data:/app/data
    restart: unless-stopped
    network_mode: bridge