[server]
port=8501
enableCORS=false

[theme]
base="dark"
primaryColor="#4267B2"
backgroundColor="#000000"
secondaryBackgroundColor="#4267B2"
textColor="#FFFFFF"
font="sans serif"

[browser]
gatherUsageStats=false
serverAddress="0.0.0.0"
serverPort=8501
